### ISSUE TITLE
create_dynamic_frame_from_options encoding

### ISSUE THREAD

**Issue by jhonnattan123** [awslabs/aws-glue-libs#105]
¿is it possible to **include the encodig** in the method **create_dynamic_frame_from_options**?

```python
sourceDyf = glueContext.create_dynamic_frame_from_options(
    connection_type="s3",
    format="csv",
    connection_options={
        "paths": ["s3://bucket/folder"]
    },
    format_options={
        "withHeader": True,
        "separator": ","
    }
)
```

**Comment by moomindani** [comment]
We apologize for delay.

Currently we only support UTF-8 for `create_dynamic_frame.from_options` method with some exception.
Instead, you can use Spark DataFrame on Glue Spark job. Here's the sample script: https://github.com/aws-samples/aws-glue-samples/blob/master/examples/converting_char_encoding.md
