### ISSUE TITLE
GlueContext.write_dynamic_frame.from_options

### ISSUE THREAD

**Issue by theonlyway** [awslabs/aws-glue-libs#108]
Is it possible to specify when writing the dynamicframe out to S3 that we can pick the storage class to throw it in in S3?

```
glueContext.write_dynamic_frame.from_options(frame=dynamicFrame, connection_type="s3", connection_options={
            "path": s3PathLatest, "StorageClass": "STANDARD_IA"}, format="csv", format_options={"separator": ",", "writeHeader": True, "optimizePerformance": True}, transformation_ctx=f"{table['Name']}_dataSink")
```

There doesn't seem to be an actual documentation on what the `connection_options` dict actually supports and looking over the code library it doesn't actually really care what you throw in there.

**Comment by moomindani** [comment]
We do not have that capability for now.
We filed this as a feature request. We appreciate your feedback.
