### ISSUE TITLE
Filter class is missing

### ISSUE THREAD

**Issue by Kkari** [awslabs/aws-glue-libs#11]
I see that this library hasn't been updated in a while, which is a shame because I find it really useful.
The Filter class is missing from the lib entirely

**Comment by glue-dev-galazzah** [comment]
Thank you for reaching out! The repository has been updated to reflect the newest code. You can find the `Filter` class [here](https://github.com/awslabs/aws-glue-libs/blob/master/awsglue/transforms/dynamicframe_filter.py). In the future, this repository will be more up to date.
