### ISSUE TITLE
Update this repo to match the latest PyGlue.zip

### ISSUE THREAD

**Issue by radix** [awslabs/aws-glue-libs#12]

**Comment by datavisorqiangdu** [comment]
Really need so, this repo is quite old, the Glue office document is not quite detailed.

**Comment by glue-dev-galazzah** [comment]
Thank you for reaching out. The code has been updated. In the future, the repo will stay more up to date.

**Comment by radix** [comment]
hi @glue-dev-galazzah, please see #13. The repo is still out of date compared to the latest PyGlue.zip, but PR #13 brings it fully up-to-date.
