### ISSUE TITLE
Support rootTag from spark-xml

### ISSUE THREAD

**Issue by joekendal** [awslabs/aws-glue-libs#146]
[Spark-xml](https://github.com/databricks/spark-xml) has a configuration option for `rootTag`. For some reason this wasn't included in Amazon's fork.

```python
dyf = glue_context.create_dynamic_frame.from_options(
  format="xml",
  format_options={
    "rowTag": "INFO",
    "rootTag": "FORM"
  },
  ...
)
```

We need this option please.

**Comment by moomindani** [comment]
Thank you for the feedback. We filed this as a feature request.
