### ISSUE TITLE
Glue API for Scala

### ISSUE THREAD

**Issue by alexandredantas** [awslabs/aws-glue-libs#15]
I'm trying to write a glue script outside AWS script editor but dependencies for Scala API are missing.
Where can I find the dependency providing classes like com.amazonaws.services.glue.GlueContext, com.amazonaws.services.glue.MappingSpec and com.amazonaws.services.glue.ResolveSpec?

PS 1: Looks like issue #1517 is related
PS 2: For python I can find the library under https://github.com/awslabs/aws-glue-libs
PS 3: The issue I opened on aws-java-sdk was closed and I was told to open it here :)
https://github.com/aws/aws-sdk-java/issues/1671

**Comment by Gloix** [comment]
I'm trying to do the same. It's 2019 and still nothing.

There are some workarounds here https://stackoverflow.com/questions/49254077/how-to-set-up-a-local-development-environment-for-scala-spark-etl-to-run-in-aws but it's not official and it might conflict with other official AWS libraries. One of the users said they contacted Amazon back in march of 2018 and there is no known answer to the issue.

Is provisioning a costly dev-endpoint the only way to develop Glue ETL scripts in Scala? We want to use a powerful software development IDE like IntelliJ (Cloud9 and Jupyter don't fit into this category).

**Comment by alexandredantas** [comment]
@Gloix As I haven't got any reply, I created a gitter 8 template for Glue scripts. You can find it here:

https://bitbucket.org/alexandre_dantas/aws-glue-scala-template

This template has a glue api embedded (retrieved from development endpoint) to provide Glue types. Other AWS SDK dependencies are provided as usual (a sbt dependency).

**Comment by benMain** [comment]
Yeah, there has to be some way they could setup a private repo for customers if nothing else. Without a repository solution we are at the whim of the Support Team to tell us, "Oh yeah, there's a new version of the glue-assembly.jar"

**Comment by Freshwood** [comment]
Meanwhile there is an aws hosted glue jar available.
Example for a pom.xml
Resolver
```
    <repositories>
        <repository>
            <id>aws-glue-etl-artifacts</id>
            <url>https://aws-glue-etl-artifacts.s3.amazonaws.com/release/</url>
        </repository>
    </repositories>
```
Dependency
```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>AWSGlueETL</artifactId>		
            <version>1.0.0</version>		
        </dependency>
```

More information can be found here:
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html

**Comment by nemo83** [comment]
Does anyone manage to get it working with version 2.0.0. I am using sbt/scala and it fails to download ti artifact:

[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.amazonaws:AWSGlueETL:2.0.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/gio/.ivy2/local/com.amazonaws/AWSGlueETL/2.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/amazonaws/AWSGlueETL/2.0.0/AWSGlueETL-2.0.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/amazonaws/AWSGlueETL/2.0.0/AWSGlueETL-2.0.0.pom
[error]   not found: https://aws-glue-etl-artifacts.s3.amazonaws.com/release/com/amazonaws/AWSGlueETL/2.0.0/AWSGlueETL-2.0.0.pom

**Comment by ilyasotkov** [comment]
@nemo83 Version 2.0.0 of the library has not actually been released, it doesn't exist in the aws-glue-etl-artifacts bucket https://s3.console.aws.amazon.com/s3/buckets/aws-glue-etl-artifacts/release/com/amazonaws/AWSGlueETL/?region=us-east-1&tab=overview

I submitted AWS documentation feedback for inaccurate content.

**Comment by gauravbrills** [comment]
For those who like to use gradle here are 2 cents from me 

```
    maven { url "https://aws-glue-etl-artifacts.s3.amazonaws.com/release" }
}
dependencies {
    implementation "com.amazonaws:AWSGlueETL:1.0.0"
```

hopefully they push 2.0,0 soon
