### ISSUE TITLE
Can write_dynamic_frame_from_options support a "compression type", e.g., snappy? 

### ISSUE THREAD

**Issue by hengfengli** [awslabs/aws-glue-libs#18]
Hi there, 

I am trying to run a AWS Glue ETL job to export data from RDS to S3. Currently, it successfully does the job to export json files into S3. I am wondering if it is possible to compress the output files into snappy format. 

Thanks.

**Comment by moomindani** [comment]
We apologize for delay. 
Currently, for JSON writes, DynamicFrame writer does not support snappy compression.
Instead you can use Spark DataFrame.
