### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Gloix** [awslabs/aws-glue-libs#21]
Any news about the Python 3 version? There's less than a year left before support for Python 2.7 is dropped.

**Comment by ptbrown121** [comment]
I believe this issue was just solved with the release of Glue version 1 under the read me you will see the option to use glue 1.0 with spark 2.4.3 (https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-1.0/spark-2.4.3-bin-hadoop2.8.tgz).  This should be compatible with Python 3.

**Comment by moomindani** [comment]
We apologize for no interactions here.

Currently Python 3.7 is supported in Glue 3.0 platform. Same in corresponding aws-glue-lib's branches.
