### ISSUE TITLE
How to install the library to local machine?

### ISSUE THREAD

**Issue by frank-lzh** [awslabs/aws-glue-libs#3]
Hi, I just started to use python for a few weeks. I try to install the awsglue library to my local machine to write scripts using the AWS Glue service. However, I did not find a setup.py file in the awsglue directory. I try several ways, but none of them works.

1. 

install using pip3: **pip3 install git+https://github.com/awslabs/aws-glue-libs.git**
result: **Collecting git+https://github.com/awslabs/aws-glue-libs.git
  Cloning https://github.com/awslabs/aws-glue-libs.git to /tmp/pip-6gdpim84-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-6gdpim84-build/setup.py'**

2.

import in pycharm: **import sys
sys.path.append("/home/frank/extra_library/aws-glue-libs")
import awsglue**
result: **/usr/bin/python3.5 /home/frank/PycharmProjects/kyc/read_psql_table.py
Traceback (most recent call last):
  File "/home/frank/PycharmProjects/kyc/read_psql_table.py", line 4, in <module>
    import awsglue
  File "/home/frank/extra_library/aws-glue-libs/awsglue/__init__.py", line 13, in <module>
    from dynamicframe import DynamicFrame
ImportError: No module named 'dynamicframe'**

 I know this could be a naive question, but could you please provide some clue to me?

**Comment by 1123** [comment]
This question seems to have been closed without an answer. Still I am facing the same problem. 

Is it because one is not supposed to run aws glue jobs locally?

**Comment by villasv** [comment]
> Is it because one is not supposed to run aws glue jobs locally?

Exactly, this library is not supposed to work outside the Glue managed environment.
I usually install the [fake-awsglue](https://pypi.org/project/fake-awsglue/) so I can at least get some auto-completion, but even that isn't exactly alike the Glue environment because this package is not up to date. (https://github.com/awslabs/aws-glue-libs/issues/12, https://github.com/awslabs/aws-glue-libs/issues/11)

**Comment by jontroncoso** [comment]
@villasv how do I use that? I tried this:
```
bash-4.3# pip install fake-awsglue && pyspark

Requirement already satisfied: fake-awsglue in /usr/lib/python3.4/site-packages (0.0.0)
/usr/spark-2.0.0/bin/pyspark: line 53: python: command not found
Python 3.4.3 (default, Apr 24 2015, 18:29:10) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel).
18/11/12 02:46:33 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.0.0
      /_/

Using Python version 3.4.3 (default, Apr 24 2015 18:29:10)
SparkSession available as 'spark'.
>>> import sys
>>> from awsglue.transforms import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/awsglue/__init__.py", line 13, in <module>
    from dynamicframe import DynamicFrame
ImportError: No module named 'dynamicframe'
```

**Comment by villasv** [comment]
@jontroncoso this library (and therefore my "fake") is only compatible with Python 2.

Sorry about the lack of description in that package, I'll try to give it more info the next time I release it.

**Comment by veve90** [comment]
No update?

**Comment by janetst** [comment]
Also, see https://docs.aws.amazon.com/en_us/glue/latest/dg/aws-glue-programming-etl-libraries.html

**Comment by rfink** [comment]
> Also, see https://docs.aws.amazon.com/en_us/glue/latest/dg/aws-glue-programming-etl-libraries.html

I've tried this and am having the same error.

**Comment by porteron** [comment]
Any resolution here?

**Comment by janetst** [comment]
There is a Blog for developing locally on Windows using Docker: https://aws.amazon.com/blogs/big-data/developing-aws-glue-etl-jobs-locally-using-a-container/  I have tried this and got it to work. I am still researching how to update the docs to support Windows, if possible.

**Comment by porteron** [comment]
So it appears the only way to develop using the python `awsglue` package is by running the docker image issued by AWS.
In the container you can access this package, but apparently it is not a public thing.

**Comment by AlJohri** [comment]
FWIW, this worked for me:

```
pip3 install pyspark
pip3 install git+https://github.com/awslabs/aws-glue-libs.git
python3 -c "from awsglue.utils import getResolvedOptions"
```

I'm not using any advanced glue features though, just wanted access to the `args = getResolvedOptions(sys.argv, ["input", "output"])` method.
