### ISSUE TITLE
How to use connection from connection_options during local developing

### ISSUE THREAD

**Issue by yaroslav-serhiichuk** [awslabs/aws-glue-libs#38]
Is it possible to use connections locally?

I mean, something like this:
`write_dynamic_frame.from_jdbc_conf(frame=dynamic_frame,
                                                                    catalog_connection='my_jdbc_connection',
                                                                    connection_options={
                                                                        'dbtable': table_name,
                                                                        'database': 'dbo'},
                                                                    redshift_tmp_dir='s3://mybucket/test/users/trial_out/',
                                                                    transformation_ctx='ctx')`

**Comment by moomindani** [comment]
Yes.
The latest Docker images support JDBC connection integration natively.
https://aws.amazon.com/blogs/big-data/develop-and-test-aws-glue-version-3-0-jobs-locally-using-a-docker-container/
