### ISSUE TITLE
Query - FindMatches ML Transform - Run Local

### ISSUE THREAD

**Issue by fmadelinoIW** [awslabs/aws-glue-libs#40]
Hello,

Per comments on page https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html the FindMatches ML Transform is not included  on the aws glue libs, only available from the from the AWS Glue Job System (assuming this will be from the AWS Console).

Is there any plans on how to include the ML Transforms running local using the AWS GLue libs?

Thanks

Regards
Filipe Madelino

**Comment by moomindani** [comment]
Unfortunately we do not have such plan for now, but thank you for your feedback.
