### ISSUE TITLE
Missing new transforms

### ISSUE THREAD

**Issue by adam133** [awslabs/aws-glue-libs#48]
New transforms were added in January 2020 that don't seem to be included in these local dev packages.

https://aws.amazon.com/about-aws/whats-new/2020/01/aws-glue-adds-new-transforms-apache-spark-applications-datasets-amazon-s3/

`mergedframe = temp_dynf.mergeDynamicFrame(staging_dynf, ["id"])`

`AttributeError: 'DynamicFrame' object has no attribute 'mergeDynamicFrame'`

**Comment by calleo** [comment]
I am also missing the new transform. This lib is very helpful writing unit tests for glue jobs, but it becomes a problem if the latest glue changes are not pushed to this repository.

**Comment by DreadPirateRobertson** [comment]
@calleo I've gotten around this by spinning up a dev endpoint, and pulling the PySpark.zip (`/usr/share/aws/glue/etl/python/PyGlue.zip`) directly from it. Expanding this folder includes the source that's missing in this repo.

**Comment by ChadElias** [comment]
This works out of the box, just tested.

**Comment by moomindani** [comment]
It seems the issue has been resolved. Closing the issue.
