### ISSUE TITLE
possible to use glue catalog ?

### ISSUE THREAD

**Issue by moshir** [awslabs/aws-glue-libs#62]
Hi,

is it possible to use aws-glue-libs with Glue catalog.
I was able to read a dataframe from the glue catalog. 
However, i could not find a way to get query the catalog from spark.sql, example:
```python
spark.sql("show databases") # returns default
sparl.sql("use mydatabasefromawsglue") # pyspark.sql.utils.AnalysisException: u"Database 'mydatabasefromawsglue' not found;"

```

Any clue ?

**Comment by PaulBurridge-kcom** [comment]
You can create a DynamicFrame directly from the catalog as then use `toDF()` to convert to a DataFrame.

`
dynamic_frame = glueContext.create_dynamic_frame.from_catalog(
    database="xxx", table_name="xxx", transformation_ctx="datasource0")
data_frame = dynamic_frame.toDF()
`

**Comment by moshir** [comment]
Thank you Paul, however why is `spark.sql("show databases")` not working?

**Comment by PaulBurridge-kcom** [comment]
Just as guess but AWS have thier own [PySpark extentions](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-extensions.html) which have code to support things like the Glue Catalog and assist with authentication etc outside of these objects the normal PySpark objects are not aware of the Glue Catalog.

As the Glue Catalog is compatible with Apache Hive Metastore you may be able to connect via a method like [this](https://stackoverflow.com/a/55372534). Not tested myself, but good luck.

**Comment by svajiraya** [comment]
@moshir I think what you're trying to achieve can be done by patching the Spark build you're using. Follow the guide at https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore 

I don't have a script handy to automate this, but i have done this in the past and i can confirm that this works.

**Comment by moomindani** [comment]
The latest Docker images support Glue Data Catalog integration natively. 
https://aws.amazon.com/blogs/big-data/develop-and-test-aws-glue-version-3-0-jobs-locally-using-a-docker-container/

When you use these containers, you do not need to install the above catalog client manually.
