### ISSUE TITLE
Authentication for S3

### ISSUE THREAD

**Issue by Thijxx** [awslabs/aws-glue-libs#66]
Running the `./gluesparksubmit` does not take into account my current active profile for the AWS CLI.
I try to use S3 from this local setup but authentication is not working for me. I'd like to know how and where to apply the authentication details.

I have tried to add it to the current terminal, environemental variables, within the Python code in SparkContext() and even tried to read from a public S3 bucket which also fails. Should I be looking at Python or at the local Spark Java service for this authentication? Does it support MFA in any way? If not how do I circumvent this?

The error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o36.getDynamicFrame.
: java.nio.file.AccessDeniedException: s3://any-bucket: getFileStatus on s3://any-bucket: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: C124998732421193; S3 Extended Request ID: R9dkjshbvhjsdvzPXj/FeAwmWFxsEfmyksjbdvksdhbvksdjhbvsdVJSubkHsFnPgpgO3c=; Proxy: null), S3 Extended Request ID: R9dkjshbvhjsdvzPXj/FeAwmWFxsEfmyKOsjkybcvjhsdbvjsdhvbsoOI97DCEopaVJSubkHsFnPgpgO3c=

```

My code:
```
sc = SparkContext(environment={'AWS_ACCESS_KEY': 'my_key', 'AWS_SECRET_KEY': 'my_secret'})
glueContext = GlueContext(sc)

dfnew = glueContext.create_dynamic_frame_from_options("s3", {'paths': ["s3://any-bucket"]}, format="csv")

dfnew.show(2)

```

**Comment by ferrouswheel** [comment]
Your problem might be that the name of the secret key is wrong, it should be `AWS_SECRET_ACCESS_KEY`.

In addition, I'm not sure about the whether the `environment` parameter sets the variable for the master node as well?

I set environment variables in the shell before I launch pyspark, and it seems to work ok.

**Comment by Thijxx** [comment]
Thanks, I removed the env. variables, it looks like they are not used anyway.

**Comment by moomindani** [comment]
Glue library uses AWS SDK for Java v1.
AWS CLI's named profile supports some additional parameters which are not supported in AWS SDK for Java v1.
e.g. SSO integration https://docs.aws.amazon.com/sdkref/latest/guide/feature-sso-credentials.html
