### ISSUE TITLE
Support for Spark 3.0.0

### ISSUE THREAD

**Issue by ledgerW** [awslabs/aws-glue-libs#74]
Hi,
Any plans for Glue to support Spark 3.0?  The co-grouped map feature is pretty handy.
Thanks!

**Comment by dagrimmy** [comment]
We would also love to see this :)

**Comment by neilagupta** [comment]
The newly released Glue 3.0 supports Spark 3.1!

**Comment by moomindani** [comment]
Let me resolve this issue since Glue 3.0 supports Spark 3.1.1 as Neil mentioned.
