### ISSUE TITLE
Glue 2.0

### ISSUE THREAD

**Issue by PawaritL** [awslabs/aws-glue-libs#84]
Hi, is there any documentation on requirements for using this library with Glue 2.0?
Are there any features of this library that are no longer supported on Glue 2.0?
Many thanks

**Comment by gcobr** [comment]
Also looking for that. Moreover, the Docker container for local dev was never released for Glue 2. The only one available in Docker Hub is for Glue 1.

**Comment by moomindani** [comment]
We apologize for delay.

The latest public doc explains how to setup it.
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html

In addition, Docker image for Glue 3.0/2.0 is available officially.
Here's the blog post for that. https://aws.amazon.com/blogs/big-data/develop-and-test-aws-glue-version-3-0-jobs-locally-using-a-docker-container/
