### ISSUE TITLE
How set up IAM role for the JOB?

### ISSUE THREAD

**Issue by brans-cere** [awslabs/aws-glue-libs#89]
Hi. Can you please explain how to pass IAM role for the Glue job
    sc = SparkContext()
    glueContext = GlueContext(sc)
    spark = glueContext.spark_session
    job = Job(glueContext)
    job.init("test_job_pv")

Can't find parametrs to set it up like in the UI.

**Comment by moomindani** [comment]
For the local usage of aws-glue-lib, it uses default credential chain supported in AWS SDK for Java v1.
