### ISSUE TITLE
Syntax error in Python 3

### ISSUE THREAD

**Issue by GergelyKalmar** [awslabs/aws-glue-libs#91]
The following line contains a syntax error in Python 3:

https://github.com/awslabs/aws-glue-libs/blob/master/awsglue/dynamicframe.py#L119

The print statement should be replaced with the print function.

**Comment by calleo** [comment]
Use glue-1 och glue-3 branch. Master is python 2.

**Comment by GergelyKalmar** [comment]
Ah, okay! Thank you, that should work.
