### ISSUE TITLE
No Docker image for glue 3.0 local development

### ISSUE THREAD

**Issue by LeoPastaBuddy** [awslabs/aws-glue-libs#96]
Currently I looks like the only option for pySpark development with Glue 3.0 is using Development Endpoint? Local installation is not working due to the lack of pyspark in amazon's tarball (#94) and the only docker image is for Glue 1.0, which is now significantly different than Glue 3.0.

Development using Development Endpoint is quite expensive and the productivity is not the same.

**Comment by mcampora** [comment]
I tried to build an image:
- following the instructions available at https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html
- and the extra steps captured at https://github.com/webysther/aws-glue-docker

a/ spark-3.1.1-amzn-0-bin-3.2.1-amzn-3 is missing pyspark
b/ I installed pyspark on top however get exceptions while creating a GlueContext
java.lang.NoClassDefFoundError: com/amazonaws/services/lakeformation/model/CommitTransactionResult

**Comment by LeoPastaBuddy** [comment]
Furthermore I also found that Development Endpoint still doesn't support Glue 3.0
To be honest, I am at a loss on how people can actually target Glue 3.0 at all, would be really interested in knowing a development process for it.

**Comment by castillo-luis** [comment]
I finally spent some time to put together an image for glue 3.0 that works. 

The aws glue workers mount their spark/glue dependencies to /opt/amazon. You can make a python script to zip and dump that directory to s3 to get what you need to make an image for local dev. Just run the script on one of the glue 3.0 workers.  Make sure to set the proper python paths as well. You can dumpy the python path from one of the workers to get an idea on how it should be set. Once you have the libraries, some modification to the spark-defaults.conf will be required to set local mode and the proper credentials provider.

It shouldn’t be this hard to set up a dev environment. Not sure why this was all not tested prior to release or why they haven’t release a docker image since glue 1.0

**Comment by alrouen** [comment]
Following @castillo-luis idea, I just did this : https://github.com/alrouen/local-aws-glue-v3-zeppelin

So far, looks like to work properly

**Comment by archenroot** [comment]
@castillo-luis could you also share your dockerfile

**Comment by sshah90** [comment]
@archenroot it's available now.

Check here : https://hub.docker.com/r/amazon/aws-glue-libs/tags

**Comment by archenroot** [comment]
> @archenroot it's available now.
> 
> Check here : https://hub.docker.com/r/amazon/aws-glue-libs/tags

@sshah90 - can you please provide docker image so community can customize and build the self the image? Thank you.

**Comment by archenroot** [comment]
@sshah90 
I tried to start with:
```
docker run -itd -p 8888:8888 -p 4040:4040 \
-v ~/.aws:/root/.aws:ro \
--name glue_jupyter \
amazon/aws-glue-libs:glue_libs_3.0.0_image_01 \
/home/jupyter/jupyter_start.sh
```

I get following error in container bash:
```
^CTraceback (most recent call last):
  File "/home/glue_user/.certs/ssl_tls_setup.py", line 87, in <module>
    automated_main(keystore_path=args.keystore, keystore_pw=args.keystorepw)
  File "/home/glue_user/.certs/ssl_tls_setup.py", line 78, in automated_main
    generate_self_signed_ssl_cert(get_default_keystore_path(), keystore_pw, DEFAULT_KEY_ALIAS)
  File "/home/glue_user/.certs/ssl_tls_setup.py", line 47, in get_default_keystore_path
    instance_dns = get_instance_dns()
  File "/home/glue_user/.certs/ssl_tls_setup.py", line 14, in get_instance_dns
    instance_metadata = botoutils.get_instance_metadata()
  File "/usr/local/lib/python3.7/site-packages/boto/utils.py", line 401, in get_instance_metadata
    return _get_instance_metadata(metadata_url, num_retries=num_retries, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/boto/utils.py", line 241, in _get_instance_metadata
    return LazyLoadMetadata(url, num_retries, timeout)
  File "/usr/local/lib/python3.7/site-packages/boto/utils.py", line 251, in __init__
    data = boto.utils.retry_url(self._url, num_retries=self._num_retries, timeout=self._timeout)
  File "/usr/local/lib/python3.7/site-packages/boto/utils.py", line 217, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
KeyboardInterrupt
Error opening input file -nokeys
-nokeys: No such file or directory
Error opening input file -nokeys
-nokeys: No such file or directory
Error opening input file -nocerts
-nocerts: No such file or directory
starting org.apache.spark.deploy.history.HistoryServer, logging to /home/glue_user/spark/logs/spark--org.apache.spark.deploy.history.HistoryServer-1-67b20ab066a5.out

```

And localhost:8888 is not accessible

**Comment by sshah90** [comment]
Hi @archenroot unfortunately my use case is not running notebook so I haven' tested that command. 

I am running image with [Pycharm](https://aws.amazon.com/blogs/big-data/developing-aws-glue-etl-jobs-locally-using-a-container/) and able to run Glue codebase. 

FYI, they have change root location to `/home/glue_user/` so you have to mount aws credentials there.

**Comment by archenroot** [comment]
Is it possible to get AWS official docker file, so we can customize it for our purpose? Thx.

**Comment by castillo-luis** [comment]
@archenroot just use the aws docker image as your parent image in your own dockerfile and add/change what you need to change.

**Comment by archenroot** [comment]
:-) is there some hidden magic so I cannot see how the image is being built?

**Comment by moomindani** [comment]
Docker image for Glue 3.0 is available officially.
Here's the blog post for that. https://aws.amazon.com/blogs/big-data/develop-and-test-aws-glue-version-3-0-jobs-locally-using-a-docker-container/
