### ISSUE TITLE
How to manually add JDBC .jar files?

### ISSUE THREAD

**Issue by fedsp** [awslabs/aws-glue-libs#99]
Using glue, It is simple as pass a glue job parameter "Dependent jars path" pointing to my s3 location.

How can I do the same thing from the local container glue_libs_2.0.0_image_01?

**Comment by moomindani** [comment]
You can see the appendix of this blog post (https://aws.amazon.com/blogs/big-data/develop-and-test-aws-glue-version-3-0-jobs-locally-using-a-docker-container/) to add extra jar dependencies.
